### ISSUE TITLE
why do u use Akka 

### ISSUE THREAD

**Issue by HelloTo4x** [UniversaBlockchain/UniCherryGarden#1]
Hi, can u tell me why u choose Akka, why don't you choose project loom for Actor(like light thread), or other Reactive Programming libraries, thank you

**Comment by amyodov** [comment]
It’s not a problem just a question, so I’ll close it to don’t keep it as an issue. For discussions, feel free to join the Universa’s development Telegram chat at [@UniversaDev](https://t.me/UniversaDev) – even if this project is not a part of “Universa network”, it’s still made under Universa umbrella, so any dev discussions can happen there.

But the question is good, I’ll answer it.

First and foremost, this project is Scala-centric, not Java-centric. The most important algorithms and business logic happen on the CherryGardener/CherryPicker/CherryPlanter side; and to be as readable and convenient as possible, that side is fully written on Scala.
But it is Scala-centric, not Scala-_only_. The clients who use this system (and which use the client-side library of the CherryGardener) may be written on any language. Therefore the client side is made on “raw” Java, but with a mental attitude to specifically improve the quality-of-live for “advanced” Kotlin users (such as, the public client interfaces using nullable types instead of Java’s Optional, to make it more Kotlin-friendly; interestingly the code is still very `Optional`-heavy inside! – but the public interfaces are often `@Nullable` instead).

So, we have the primary logic in Scala (to be most straight-forward and convenient); and the client side in Java (to be most compatible with any users from other JDK-compatible languages). Any threading/networking library therefore better be as Scala-friendly as possible; but still usable from raw Java. Akka is a rather good match in this case.

There are not that many mature alternatives for “convenient networking” in Scala world. [Scala-Cats](https://typelevel.org/cats/) (+`cats-effects`)? – it is very Scala-focused and won’t help much to the Java client; and also it is very-very-very academic, hiding the cleanness of the networking business logic behind the layers and layers of theoretical beauty of category theory concepts. Here in Universa we are not so keen to write the _academic_ code that looks good on the CS lecture blackboard, with arrows and monads, we prefer to write the _practical_ code that works good. [Zio](https://zio.dev/)? – I would say it is a bit more practical, but alas it is still too much Scala-focused, and not helps much to Java side of the question.

With Akka though, we have rather established, advanced and convenient (especially when used in Scala) features for networking reactivity; and even higher-level solutions like akka-cluster (to get all parts of the system into a single self-maintained universe) and “receptionists” (to discover the parts of the system, which may register and unregister dynamically). Akka-for-Java is okay; Akka-for-Scala, on top of that, is very nicely typed (allows typing of actors by messages they receive). Some lower-level libraries – such as the HTTP clients, which do the GraphQL queries – also bind into the Akka’s main loop, for better maintenance. So, enough of high-level Scala abstractions and helpers that are very much useful practically; and good way to write in reactive way not just in Scala, but to build a Java side of the system as well.

That’s why Akka.
